### ISSUE TITLE
Support for Docker >= 1.12

### ISSUE THREAD

**Issue by heitorsilva** [open-lambda/open-lambda#10]
Hello guys!

The tag -f was deprecated on Docker v1.10, and removed on v1.12.

I was trying to run the chat application, and it didn't work:

```
Pushing image
EXEC docker tag -f yfogzxrcrdpc localhost:32768/yfogzxrcrdpc
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.
```

I'm using Docker v1.12.0-a on OS X 10.11.6. 

What I've said about Docker and the -f tag can be confirmed here:
https://github.com/docker/docker/pull/23090

I've removed the -f flag from below files and it seems to work:

```
applications/autocomplete/setup.py
applications/pyocr/setup.py
applications/pytix/setup.py
applications/stockprog/setup.py
testing/setup.py
util/setup.py
```

**Comment by edoakes** [comment]
Thank you for letting us know Heitor! We knew it was coming eventually, and
will make the necessary fixes.

**Comment by edoakes** [comment]
Working on switching to go-dockerclient for cluster management to fix this and other issues.
