### ISSUE TITLE
make test-all fails as it fails to 

### ISSUE THREAD

**Issue by ariel1995zhao** [open-lambda/open-lambda#100]
<img width="734" alt="Screen Shot 2021-06-12 at 10 18 48 PM" src="https://user-images.githubusercontent.com/31999801/121793351-45380c00-cbcc-11eb-99e5-76d8cbe62c54.png">

I can't get make test-all to work
<img width="734" alt="Screen Shot 2021-06-12 at 10 18 48 PM" src="https://user-images.githubusercontent.com/31999801/121793382-79133180-cbcc-11eb-8839-6b63606b87db.png">

However each test error seems to look similar, they each refer to a worker.pid file that they either can't access or rexognize is there but believes is not running

<img width="937" alt="Screen Shot 2021-06-12 at 10 22 11 PM" src="https://user-images.githubusercontent.com/31999801/121793424-c8f1f880-cbcc-11eb-8f59-da75f555a1b2.png">

Here are the contents of the work.pid and worker.out files.

<img width="796" alt="Screen Shot 2021-06-12 at 10 25 23 PM" src="https://user-images.githubusercontent.com/31999801/121793458-28500880-cbcd-11eb-9d26-baedc9179858.png">

I honestly have no idea where to even start debugging this -- any insight into this would be greatly appreciated

**Comment by kaimast** [comment]
It looks like you ran OL before and it didn't shut down correctly. There might still be cgroups set up or filesystems mounted in the test-dir.
The easiest way to "fix" this might be to restart your system. 

I will close this for now, but feel free to reopen.
