### ISSUE TITLE
Current Makefile can't touch empty target files since they've been removed

### ISSUE THREAD

**Issue by Eric-H-Ren** [open-lambda/open-lambda#14]
Two empty target files in ./imgs directory were deleted on Oct 13 in commit 159bf93
however Makefile wasn't changed correspondingly.
Need to either cancel timestamp tracking or make use of other existing files. Which direction to go?

**Comment by edoakes** [comment]
The empty target files were removed from the repository but the Makefile still uses them - the first time it's built 'touch' creates the files locally.

**Comment by Eric-H-Ren** [comment]
Oh right, but the './imgs' directory was deleted as well. 'touch' can't create both directory and the file. Should have kept ./imgs as an empty folder, otherwise touch fails to create new files in it.

**Comment by Eric-H-Ren** [comment]
I thought Tyler was going to get rid of this hack.
