### ISSUE TITLE
Invoke lambda from within a lambda function

### ISSUE THREAD

**Issue by nmittal18** [open-lambda/open-lambda#18]
I want to measure interLambda communication time. Is there a way to send a request to a lambda function from within a lambda function?
I tried sending http request using "python request module" but I get "no such container ..." error.
Any help would be really appreciated. Thanks.

**Comment by tylerharter** [comment]
I apologize we haven't been actively responding to these.

What is the exact call you're making via the request module?  (I would like to see the relevant code snippet).

Have you confirmed the same code that calls via the request module works when issued from the host (i.e., not inside a Lambda?).

**Comment by tylerharter** [comment]
I'm closing this to cleanup issues, but please do re-open if this is an problem in the future (we'll try to be more responsive next time).
