### ISSUE TITLE
Handler Isolation

### ISSUE THREAD

**Issue by Gnep** [open-lambda/open-lambda#2]
Hi,

I am curious how OpenLamda isolates multi-tenancts' handlers, given that container is not considered secure.

**Comment by tylerharter** [comment]
I agree, OpenLambda security is only as good as cgroup security, and that's less secure than VMs.  However, it appears AWS Lambda also uses containers: https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/.

**Comment by Gnep** [comment]
@tylerharter 

Thanks for answering. The reason I asked is because the project I'm working on: http://www.hypercontainer.io/. 

Put simply, HyperContainer is a hypervisor-based Docker runtime. It allows you to launch a micro VM based on Docker image in ~100ms. Fast as Container, Secure as VM.

I am interested to see how to integrate HyperContainer with Serverless frameworks.
