### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by reiz** [open-lambda/open-lambda#21]
I just followed the instructions in the README. Cloned the project and executed `make`. After a while this error occurred: 

```
# github.com/open-lambda/open-lambda/worker/sandbox
../sandbox/sandboxFactory.go:169:21: undefined: syscall.MS_BIND
../sandbox/sandboxFactory.go:169:39: undefined: syscall.MS_REC
../sandbox/sandboxFactory.go:172:19: undefined: syscall.Mount
../sandbox/sandboxFactory.go:174:19: undefined: syscall.Mount
make: *** [bin/admin] Error 2
```

It seems that a Go dependency is broken.

**Comment by tylerharter** [comment]
I apologize we haven't been actively responding to github issues.  Are you still hitting this?

What go version are you using?  The quickstart/deps.sh scripts specifically uses 1.7.6 (perhaps the syscall library doesn't have those members in earlier versions?).

**Comment by tylerharter** [comment]
I'm closing this to cleanup issues, but please do re-open if this is an problem in the future (we'll try to be more responsive next time).
