### ISSUE TITLE
Handle Startup Latency more Robustly

### ISSUE THREAD

**Issue by tylerharter** [open-lambda/open-lambda#37]
The test targets (in the Makefile) have this snippet:

        @echo "Sleeping (to wait for worker setup)..."
        @sleep 15
        @echo "Requesting lambdas..."

On my VM (a 1GB DigitalOcean droplet), I need to increase that timer to 60 seconds for the tests to work.

The biggest source of latency seems to be the following call in handler.go, which takes 60 seconds:

       pip.InitInstallManager(opts)

I have two suggestions for handling this robustly:

1. Let's poll the localhost:8080/status call rather than wait a fixed time.  The status route is not registered (with ListenAndServe) until NewServer (the call responsible for most setup) returns, so when a successful call is made to /status, we can know the worker is ready.
2. Let's print out bootup progress to the log.  In particular, can we add a message at each step of the NewHandlerManagerSet method?

**Comment by edoakes** [comment]
https://github.com/open-lambda/open-lambda/commit/d9f4adc1f10ead5bc18e89b558ef77d80ec7faa1
