### ISSUE TITLE
build openlambda error

### ISSUE THREAD

**Issue by Ddnirvana** [open-lambda/open-lambda#42]
Hi guys, 

Thanks for your great contributions on this project!
I am interested about the project and trying to use it.
However, I meet some problems while compiling.

I finish the dependency by invoking
<pre>
$ sudo -E -s ./quickstart/deps.sh
</pre>
And it seems all right.

Now I checked the environment.
<pre>
$ python --version
Python 3.5.2

$ go version
go version go1.7.6 linux/amd64

$ docker --version
 Docker version 1.6.2, build 7c8fca2

$ lsb_release -d
Description: Ubuntu 14.04.5 LTS

$ uname -r
4.8.17
</pre>

And when try `sudo -E -s make test-all`
I meet the following error messages
<pre>
cd hack/go/src/github.com/open-lambda/open-lambda/worker/admin && /home/dd/devlop/serverless/open-lambda/hack/go.sh install
Using GOPATH=/home/dd/devlop/serverless/open-lambda/hack/go
+ go install
# runtime
/usr/local/go/src/runtime/float.go:45: float64bits redeclared in this block
        previous declaration at /usr/local/go/src/runtime/fastlog2.go:33
/usr/local/go/src/runtime/os_linux.go:367: rt_sigaction redeclared in this block
        previous declaration at /usr/local/go/src/runtime/cgo_sigaction.go:20
/usr/local/go/src/runtime/signal_sighandler.go:15: crashing redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal_amd64x.go:39
/usr/local/go/src/runtime/signal_sighandler.go:28: sighandler redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal_amd64x.go:44
/usr/local/go/src/runtime/sizeclasses.go:75: _MaxSmallSize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/malloc.go:124
/usr/local/go/src/runtime/sizeclasses.go:79: _NumSizeClasses redeclared in this block
        previous declaration at /usr/local/go/src/runtime/malloc.go:121
/usr/local/go/src/runtime/sizeclasses.go:80: _PageShift redeclared in this block
        previous declaration at /usr/local/go/src/runtime/malloc.go:107
/usr/local/go/src/runtime/sizeclasses.go:83: class_to_size redeclared in this block
        previous declaration at /usr/local/go/src/runtime/msize.go:49
/usr/local/go/src/runtime/sizeclasses.go:84: class_to_allocnpages redeclared in this block
        previous declaration at /usr/local/go/src/runtime/msize.go:50
/usr/local/go/src/runtime/sizeclasses.go:86: divMagic redeclared in this block
        previous declaration at /usr/local/go/src/runtime/msize.go:225
/usr/local/go/src/runtime/sizeclasses.go:86: too many errors
make: *** [bin/admin] Error 2
</pre>

Could you please help me to fix this compile issues?

Any advices are welcomed!! Thanks very much!

**Comment by rushins** [comment]
i too get similar errors like below.

======================================================================
ERROR: test_with_no_cache (sock_test.SockTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lroot/open-lambda/testing/integration-tests/sock_test.py", line 18, in test_with_no_cache
    run_cluster_test_with_conf(conf)
  File "/home/lroot/open-lambda/testing/integration-tests/cluster_test_utils.py", line 88, in run_cluster_test_with_conf
    run_lambda('echo')
  File "/home/lroot/open-lambda/testing/integration-tests/cluster_test_utils.py", line 60, in run_lambda
    + 'with status code {status}.'
TypeError: bad operand type for unary +: 'str'

----------------------------------------------------------------------
Ran 6 tests in 198.095s

FAILED (errors=4)
Makefile:41: recipe for target 'test-all' failed
make: *** [test-all] Error 1
-----------------

any idea to fix.

**Comment by edoakes** [comment]
Hi @rushins, I think there were a few issues with a rewriting of the tests that we did.

Could you please try re-running the tests on the most recent commit (b709a563691c0b68e455ae667ffa8de2e80f69e6)?

If you still see issues, please post the output of `make test-sock-all` here.

**Comment by rushins** [comment]
ok i ran the the following   commands on the fix you sent 
 rm -f imgs/lambda  , 
rm -rf testing/test_worker 
sock-init.c
	gcc -Wall sock-init.c -o sock-init
	cp sock-init /usr/local/bin/sock-init
 
After i got this below, seems no error this time

Worker ready. Requesting lambdas...
.
----------------------------------------------------------------------
Ran 6 tests in 68.295s

OK

is this how it should be now ?

**Comment by edoakes** [comment]
That seems right. Did you run those commands manually? You shouldn't need to. `make clean && make` should do about the same thing.

**Comment by rushins** [comment]
ok thanks. by the way , do you have GOLANG examples with open-lambda since  the architect and deployment used "GO"  code.

**Comment by edoakes** [comment]
I'm not sure I understand your question. The worker is written in Golang (see https://github.com/open-lambda/open-lambda/tree/master/worker). Serverless functions are written in Python (see https://github.com/open-lambda/open-lambda/tree/master/testing/registry).

**Comment by rushins** [comment]
i mean "framework example using golang in openlambda" . similar to what  aws lambda offers with GOLANG below link

https://serverless.com/blog/framework-example-golang-lambda-support/
