### ISSUE TITLE
deprecated and removed startcontainer API

### ISSUE THREAD

**Issue by YellyYU** [open-lambda/open-lambda#43]
Hi guys,

I'm beginning to explore your project and encountered some problems.

I setup the environment following the instructions in https://open-lambda.org/doc.htm and tried testing the project with commands listed in p109 of slides(https://open-lambda.org/resources/slides/ol-first-meeting.pdf).

My trouble comes with the last "make test" (I ran it with sudo) command.

For every test application, the client.Do(req) function (line 41 of worker/server_test.go) returns error: API error (400): {"message":"starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24"}

I removed the second parameter(container.ID) to cm.client.StartContainer() function (line 275 of worker/container/dockerManager.go), but then the compiler complaints with "container/dockerManager.go:276: not enough arguments in call to cm.client.StartContainer"

As I assume the StartContainer function is contained in the imported docker from "github.com/fsouza/go-dockerclient" as is suggested in the import section of the go file, I wondered if it is a matter of inconsistent docker version, such that the imported docker does not reflect the newest API version.

I made several efforts to specify the imported docker version, such as append "github.com/fsouza/go-dockerclient" with "@v1.2.2" in worker/Godeps/Godeps.json, but with no success.

So, if anyone could kindly help me with this problem, I will be very grateful.

**Comment by edoakes** [comment]
Please follow the instructions in the README in the repository, not those on the website (they are very out of date).
