### ISSUE TITLE
Question about sharing runtime in OpenLambda

### ISSUE THREAD

**Issue by lioncruise** [open-lambda/open-lambda#47]
I read the [OpenLambda](https://www.usenix.org/system/files/conference/hotcloud16/hotcloud16_hendrickson.pdf) paper in HotCloud'16.  There is a description about sharing language runtime in OpenLambda.

>  Handlers are typically written in languages such as JavaScript or Python; by sharing the runtime environment across functions, the code specific to a particular application will typically be small, and hence it is inexpensive to send the handler code to any worker in a cluster.

![20181226191303](https://user-images.githubusercontent.com/12690984/50444230-516b7880-0942-11e9-8247-6a2ebc80d93b.png)

I consider the app as a process, usually isolated by container. In the third container mode, I consider the  runtime should be loaded into a specific process's memory area. Each process has its own independent memory address space. So, I wonder how you implement such language runtime sharing in OpenLambda? Besides, I have several questions.

1. Is sharing runtime a common operation in those major commercial and open source serverless platforms?
2. In this mode, what is the relationship between third-party software packages loaded in memory and the runtime? Are packages shared by all app or belong to a specific process? 
3. Are there only read-only operations in runtime and third-party packages? I think the operation of sharing runtime and packages is not appropriate if there is a writting operation.

**Comment by edoakes** [comment]
That paper is very outdated. Reading the following should clarify things:

https://www.usenix.org/conference/atc18/presentation/oakes

**Comment by lioncruise** [comment]
@edoakes The SOCK paper mentioned using Zygotes provisioning to eliminate the time of loading and initializing Python runtime and packages, but I think it's not appropriate calling this approach "shared runtime". Your opinion?

**Comment by tylerharter** [comment]
The sharing is referring to physical memory for the runtime, which is shared on a copy-on-write basis between different lambdas.  There's no logical sharing, of course.  Is there something better to call it?
