### ISSUE TITLE
Question about scraping Python projects from GitHub in SOCK paper

### ISSUE THREAD

**Issue by lioncruise** [open-lambda/open-lambda#48]
I read the [SOCK](https://www.usenix.org/system/files/conference/atc18/atc18-oakes.pdf) in ATC'18, and have some questions about scraping Python projects from GitHub mentioned in the paper.

> We now consider the types of packages that future lambda applications might be likely to use, assuming efficient platform support. We scrape 876K Python projects from GitHub and extract likely dependencies on packages in the popular Python Package Index (PyPI) repository, resolving naming ambiguity in favor of more popular packages. 

1. How do you specify these 876K Python projects to scrape?
2. How do you analyse these projects's dependencies? I don't know whether all these Python projects have a requirement.txt dependencies.

**Comment by edoakes** [comment]
1) They were all publicly listed projects tagged as 'Python' at the time that we performed the study.

2) Used Python AST parsing to identify import statements, inferred packages based on imported package name (this is could be noisy). Resolved naming ambiguity in favor of more popular packages.
