### ISSUE TITLE
failed to install 

### ISSUE THREAD

**Issue by ichigoXZ** [open-lambda/open-lambda#52]
```
uname -a
Linux beer 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
failed to install dependencies as dep.sh suggested.
First, Cannot add PPA: 'ppa:~ubuntu-lxc/ubuntu/lxd-stable'. The team named '~ubuntu-lxc' has no PPA named 'ubuntu/lxd-stable', I tried
```
apt install -t xenial-backports linux-image-extra-$(uname -r)
```
but it didn't work.
so I skipped this step,  then docker-engine can't be found,
I installed docker-ce instead, following docker official documents.
when I run make , I got
```
Killing worker if running...
./bin/admin kill -cluster=testing/test-cluster;rm -rf testing/test-cluster/workers/*
Kill worker process with PID 22596
os: process already finished
Failed to kill process with PID 22596.  May require manual cleanup.

Starting worker...
./bin/admin setconf -cluster=testing/test-cluster  '{"sandbox": "sock", "handler_cache_size": 0, "import_cache_size": 0, "cg_pool_size": 10}'
./bin/admin workers -cluster=testing/test-cluster
Started worker: pid 23895, port 8080, log at /home/between/Between/open-lambda/testing/test-cluster/logs/worker-0.out

Waiting for worker to initialize...
2019/03/25 17:03:57 At least one worker failed the status check
2019/03/25 17:03:59 At least one worker failed the status check
...
2019/03/25 17:05:55 At least one worker failed the status check
Worker failed to initialize after 60s
Makefile:108: recipe for target 'test-sock-nocache' failed
make: *** [test-sock-nocache] Error 
```

what should I do to have it installed on my ubuntu16.04

**Comment by tylerharter** [comment]
Perhaps the best way to get setup currently is from our AWS image: https://github.com/open-lambda/testing#development-vm.

We also have the Vagrant files we used to create that image if you want to setup a local environment: https://github.com/open-lambda/testing/tree/master/dev-build.

Unfortunately, the Vagrantfiles are probably a more up-to-date description of the dependencies than deps.sh.
