### ISSUE TITLE
Question about the branch about open-lambda.

### ISSUE THREAD

**Issue by Violet-Guo** [open-lambda/open-lambda#85]
Hi,

I want to use open-lambda for some experiments. However, the branch of master and v0.1.1 fully confused me. 

What's the difference between these two branches?
Which version should I use? Because v0.1.1 looks like out of date compared with master branch.

Thank you for your help!

**Comment by tylerharter** [comment]
We haven't done a release for a while.  I would look at the tests here: https://s3.us-east-2.amazonaws.com/open-lambda-public/tests.html.  Then choose a commit from the master branch that is passing tests.
