### ISSUE TITLE
How to mount a directory 

### ISSUE THREAD

**Issue by 123toorc** [open-lambda/open-lambda#94]
Fantastic team,
         I'm running open-lambda for video processing test, the question is how can I mount a host directory to the directory inside the docker container? which part of code I can do the setup? I didn't find any "docker run" command in order to mount the volume. I put my file inside "./default-ol/lambda/home/" and set my path in my code is "/home" which was worked, but when I do write in my code to the same path, it doesn't work.  
Best and thank you
Tong

**Comment by tylerharter** [comment]
Hi Tong,

Does the docker backend have an advantage over SOCK (https://www.usenix.org/system/files/conference/atc18/atc18-oakes.pdf) for your use case?  Just curious if SOCK is lacking something you need, as that's what I hope people will generally use.

There's not really a way to configure it to have another mount, but if you're just prototyping something, the easiest way would be to add another volume here:

https://github.com/open-lambda/open-lambda/blob/master/src/sandbox/dockerPool.go#L77

Tyler

**Comment by 123toorc** [comment]
Hi Tyler,

	Thank you so much for reply so fast! I saw the code, it looks like the handler directory is already mounted to host file system? So in container, it path is “/“ or “/handler”? so I can put my stuff in this directory in order to be processed, am I correct? I’m not familiar with Go, so if it is ok I will just use it, I’m working on some benchmark, we feel like to add lambda inside is more good idea. Thank you for your work! 

Thanks, 
Tong

**Comment by tylerharter** [comment]
Sure, if the video data doesn't change from invocation to invocation, you could bundle it with the code (which will get mounted to /handler).  In that case, you wouldn't even need to change the source code.

Maybe this doc helps?  https://github.com/open-lambda/open-lambda/blob/master/src/lambda/code_puller.md.  You could put both your code and static content in a .tar.gz.

Of course, this means it's copied each time a new lambda instance gets spun up.  If you somehow want them to share something on the host, you'll need to change the code to have that shared mount.

Feel free to close the issue if this solves the problem.

**Comment by 123toorc** [comment]
Hi Tyler
            One more question, is that possible I can return back a file?
is there any API from open lambda I can use?
Best


Tyler Harter <notifications@github.com> 于2020年2月6日周四 下午4:33写道：

**Comment by 123toorc** [comment]
nevermind.. I use ftp anyways. thanks, I will close the question.

Tong Xing <123toorc@gmail.com> 于2020年2月6日周四 下午5:50写道：

**Comment by tylerharter** [comment]
Thanks for the update!
