### ISSUE TITLE
make test all failed - "using existing OL directory"

### ISSUE THREAD

**Issue by MjavadBakhshi** [open-lambda/open-lambda#95]
Hi to all
i  have  ran make test-all after installed open lambda successfully
but just 1 test passed and 17 tests failed and when i was checking errors i encountered a same error for all failed tests with following content:
""using existing OL directory at /usr/local/open-lambda/test-dir2"
"previous worker may be running, /usr/local/open-lambda/test-dir2/worker/worker.pid already exists"

hot machine : ubuntu 18
docker version :
18.09.7
go version:
go version go1.13.8 linux/amd64
i installed ubuntu along side windows 10

can any one help me  to fix these errors?

thanks.

**Comment by GindaChen** [comment]
**Quick solution**
1. Try `kill $(cat worker.pid); rm worker.pid`, and try to run a worker. If not success
2. Try `ps -C ol -o pid=` and see if there is a pid. If yes, `kill <pid>`. 

**Explaination**
`worker.pid` is like the lock file for a `ol worker`. If you `cat worker.pid`, you shall see a process id indicating the running worker. But in unexpected cases, forceful kill will kill the process, leaving the `worker.pid` dangled and never cleanedup. 

First, let's see if that process is still alive. If so, killing it and remove that file shall rock.

If not, then we check if there is a worker running: `ps -C ol`. This will output all process with name `ol` hence the running worker `pid`. Killing it shall free the environment of all ol worker.

I'm raising a PR to resolve this. (Also to @tylerharter)

**Comment by MjavadBakhshi** [comment]
@GindaChen  thanks for response
i did it .
1. remove old open-lambda 
2. clone open-lambda from mentioned repo
3.run make test-all in open-lambda folder
4. resul ; pass 1 test (ping) and another failed with same that  error
5. i found worker.pid in test-dir folder and kill procee and remove file
6. run ps ol ... nothing print in terminal
my problem still stay there.
please help me what is reason when run make test-all give me this error:/

**Comment by tylerharter** [comment]
We're only really trying to support one config currently, which is Ubuntu 16.04 LTS and Go 1.12.5.  I would recommend using a VM, built using these installs: https://github.com/open-lambda/testing/blob/master/dev-build/bootstrap2.sh.  It will be cool if you can get it working with WSL, but that's not really a deployment option we imagine.

Of course, the path of least resistance to spin up an EC2 instance from AMI image we test every night: https://github.com/open-lambda/testing/blob/master/dev-build/ami.txt
