### ISSUE TITLE
How can i run multiple workers in open-lambda

### ISSUE THREAD

**Issue by MjavadBakhshi** [open-lambda/open-lambda#99]
hi to all.
how can i run multiple workers and how can configure each worker has which port?
i know that can change worker configuration in config.json file placed in deault-ol/config.json
but i dont know how can change it to run multiple workers

thanks for answers.

**Comment by balvansh** [comment]
Hey. 
First, create your OL environment, copy these n number of environments, rename them, configure their ports, and then using ./ol worker command start all your workers.

**Comment by kaimast** [comment]
I'm closing this issue as the question was answered.
